kind: Deployment
apiVersion: apps/v1
metadata:
  name: galsandbox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: galsandbox
  template:
    metadata:
      labels:
        app: galsandbox
    spec:
      containers:
        - name: galsandbox
          image: >-
            agustinlare/galsandbox
          ports:
            - containerPort: 8080
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
---
apiVersion: v1
kind: Service
metadata:
  name: galsandbox-service
  labels:
    app: galsandbox
spec:
  type: LoadBalancer
  selector:
    app: galsandbox
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 8080
