name: CD

on:
  pull_request:
    types: [opened, synchronize]
    branches: 
      - main

env:
  DOCKER_IMAGE: "agustinlare/galsandbox"
  DOCKER_TAG: ${{ github.sha }}

jobs:
  deplyo-to-linode:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true

    steps:
      - name: Kubernetes apply
        run: echo "Hello, world!" ${{ env.DOCKER_IMAGE }}:${{ env.DOCKER_TAG }}

      # - name: Checkout code
      #   uses: actions/checkout@v2

      # - name: Kubernetes set context
      #   uses: Azure/k8s-set-context@v1
      #   with:
      #     method: kubeconfig
      #     kubeconfig: ${{ secrets.KUBE_CONFIG }}

      # - name: Kubernetes apply
      #   run: |
      #     kubectl apply -f ./manifest.yaml
      
  reopen-pr:
    runs-on: ubuntu-latest
    if: failure()
    needs: deplyo-to-linode

    steps:
      - name: Reopen Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: Reopening Pull Request
          body: |
            This pull request was automatically reopened because the merge failed.
          branch: ${{ github.event.pull_request.head.ref }}
          base: ${{ github.event.pull_request.base.ref }}