name: Build and Push Docker Image

on:
  pull_request:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest

    env:
      DOCKER_IMAGE: "agustinlare/galsandbox:${{ github.sha }}"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install kubeval
        run: |
          curl -LO "https://github.com/instrumenta/kubeval/releases/latest/download/kubeval-linux-amd64.tar.gz"
          tar xf kubeval-linux-amd64.tar.gz
          sudo install kubeval /usr/local/bin/
          rm kubeval-linux-amd64.tar.gz

      - name: Validate Kubernetes manifest
        run: kubeval manifest.yaml

  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: $DOCKER_IMAGE

  scan-image:
    runs-on: ubuntu-latest

    steps:
      - name: Scan Docker image
        uses: docker/scan-action@v1
        with:
          image-ref: $DOCKER_IMAGE
      
      - name: Set output docker image
        id: output
        run: echo "::set-output name=docker_image::$DOCKER_IMAGE"