name: Merge to main

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  deplyo-to-linode:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Kubernetes set context
        uses: Azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBE_CONFIG }}

      - name: Kubernetes apply
        run: |
          kubectl apply -f ./manifest.yaml