name: CICD

on:
  pull_request:
    types: [opened, synchronize, closed]
    branches: 
      - main

env:
  DOCKER_IMAGE: "agustinlare/galsandbox"
  DOCKER_TAG: ${{ github.sha }}

jobs:
  validate-yaml:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == false

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Echo enviroment variable
        run: echo ${{env.DOCKER_IMAGE}}:${{ env.DOCKER_TAG }}

      - name: Install kubeval
        run: |
          curl -LO "https://github.com/instrumenta/kubeval/releases/latest/download/kubeval-linux-amd64.tar.gz"
          tar xf kubeval-linux-amd64.tar.gz
          sudo install kubeval /usr/local/bin/
          rm kubeval-linux-amd64.tar.gz

      - name: Validate Kubernetes manifest
        run: kubeval manifest.yaml

  build-and-push:
    runs-on: ubuntu-latest
    needs: validate-yaml
    if: github.event.pull_request.merged == false

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.DOCKER_IMAGE }}:${{ env.DOCKER_TAG }}

  scan-image:
    runs-on: ubuntu-latest
    needs: build-and-push
    if: github.event.pull_request.merged == false

    steps:
        - name: Scan for vulnerabilities
          run: echo "Hello, world!" ${{ env.DOCKER_IMAGE }}:${{ env.DOCKER_TAG }}

  deplyo-to-linode:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true

    env:
      DOCKER_IMAGE: "agustinlare/galsandbox"
      DOCKER_TAG: ${{ github.sha }}

    steps:
      - name: Kubernetes apply
        run: echo "Hello, world!" ${{ env.DOCKER_IMAGE }}:${{ env.DOCKER_TAG }}

      # - name: Checkout code
      #   uses: actions/checkout@v2

      # - name: Kubernetes set context
      #   uses: Azure/k8s-set-context@v1
      #   with:
      #     method: kubeconfig
      #     kubeconfig: ${{ secrets.KUBE_CONFIG }}

      # - name: Kubernetes apply
      #   run: |
      #     kubectl apply -f ./manifest.yaml

  notify-on-discord:
    runs-on: ubuntu-latest
    needs: deplyo-to-linode

    steps:
      - name: Send Discord Notification
        if: ${{ github.event.state == 'success' || github.event.state == 'failure' }}
        run: |
          message="Workflow ${{ github.workflow }} finished with status ${{ job.status }}"

          curl -H "Content-Type: application/json" \
          -X POST \
          -d "{\"content\":\"$message\"}" \
          ${{ secrets.DISCORD_WEBHOOK_URL }}
      
  reopen-pr:
    runs-on: ubuntu-latest
    if: failure() && github.event.pull_request.merged == true
    needs: deplyo-to-linode

    steps:
      - name: Reopen Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: Reopening Pull Request
          body: |
            This pull request was automatically reopened because the merge failed.
          branch: ${{ github.event.pull_request.head.ref }}
          base: ${{ github.event.pull_request.base.ref }}

  