name: CICD

on:
  pull_request:
    types: [closed]
    branches: 
      - main

env:
  DOCKER_IMAGE: "agustinlare/galsandbox"
  DOCKER_TAG: ${{ github.sha }}

jobs:
  validate-yaml:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Echo enviroment variable
        run: echo ${{env.DOCKER_IMAGE}}:${{ env.DOCKER_TAG }}

      - name: Install kubeval
        run: |
          curl -LO "https://github.com/instrumenta/kubeval/releases/latest/download/kubeval-linux-amd64.tar.gz"
          tar xf kubeval-linux-amd64.tar.gz
          sudo install kubeval /usr/local/bin/
          rm kubeval-linux-amd64.tar.gz

      - name: Validate Kubernetes manifest
        run: kubeval manifest.yaml
  
  code-quality:
    runs-on: ubuntu-latest

    steps:
      - name: Quality gate action
        run: "No encontre uno que sea gratis"

  build-and-push:
    runs-on: ubuntu-latest
    needs: [validate-yaml, code-quality]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.DOCKER_IMAGE }}:${{ env.DOCKER_TAG }}

  scan-image:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Scan for vulnerabilities
        uses: crazy-max/ghaction-container-scan@v2
        with:
          image:  ${{ env.DOCKER_IMAGE }}:${{ env.DOCKER_TAG }}

  promote:
    runs-on: ubuntu-latest
    needs: scan-image

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull Docker image
        run: docker pull ${DOCKER_IMAGE}:${DOCKER_TAG}

      - name: Retag Docker image
        run: |
          docker tag ${DOCKER_IMAGE}:${DOCKER_TAG} ${DOCKER_IMAGE}:latest
          echo "::set-output name=retagged-image::${DOCKER_IMAGE}:latest"
          
  deplyo-to-linode:
    runs-on: ubuntu-latest
    needs: promote

    steps:
      - name: Kubernetes apply
        run: echo "Hello, world!" ${{ env.DOCKER_IMAGE }}:latest

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Kubernetes set context
        uses: Azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBE_CONFIG }}

      - name: Kubernetes apply
        run: |
          kubectl apply -f ./manifest.yaml

  notify-on-discord:
    runs-on: ubuntu-latest
    needs: deplyo-to-linode
    if: failure() || success()

    steps:
      - name: Send Discord Notification
        run: |
          echo "Hello"
          message="Workflow ${{ github.workflow }} finished with status ${{ job.status }}"

          curl -H "Content-Type: application/json" \
          -X POST \
          -d "{\"content\":\"$message\"}" \
          ${{ secrets.DISCORD_WEBHOOK_URL }}
      
  reopen-pr:
    runs-on: ubuntu-latest
    if: failure()
    needs: deplyo-to-linode

    steps:
      - name: Reopen Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: Reopening Pull Request
          body: |
            This pull request was automatically reopened because the merge failed.
          branch: ${{ github.event.pull_request.head.ref }}
          base: ${{ github.event.pull_request.base.ref }}

  